Ignition 8.0 (beta) failed to start module: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
Updated to java.time.Instant - Java 8+
http://openjdk.java.net/jeps/150